---
- name: get_url OracleLinux 6 repo
  get_url: url={{item}} dest=/etc/yum.repos.d
  with_items:
    - http://public-yum.oracle.com/public-yum-ol6.repo
  when: ansible_distribution_major_version|int == 6
  tags: oraclelinux

- name: get_url OracleLinux 6 gpg
  get_url: url={{item}} dest=/etc/pki/rpm-gpg/RPM-GPG-KEY-oracle
  with_items:
    - http://public-yum.oracle.com/RPM-GPG-KEY-oracle-ol6
  when: ansible_distribution_major_version|int == 6
  tags: oraclelinux

- name: disable OracleLinux 6 repo
  replace: >
    dest=/etc/yum.repos.d/public-yum-ol6.repo
    regexp='^enabled=1'
    replace='enabled=0'
  tags: oraclelinux

